### ISSUE TITLE
Firebase (~> 3.17.0) required by Podfile

### ISSUE THREAD

**Issue by rugdealer** [NativeScript/template-master-detail-ng#10]
Ran the following command.

`tns create my-app --template https://github.com/NativeScript/template-master-detail-ng.git#master --appid org.nativescript.masterdetail`

I set all the Firebase configs to the default "no".

Then `cd my-app`
Finally `tns run ios`

This is the error I received. Never used Firebase before, and I don't think I'll need it for this project. Anyway on removing it completely? Thanks

```
[!] Unable to satisfy the following requirements:

- `Firebase (~> 3.17.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Firebase (~> 3.17.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
Processing node_modules failed. Error: Command pod failed with exit code 31 Error output: 

```

**Comment by manoldonev** [comment]
Hey @rugdealer,

This template is currently work-in-progress and as described in the readme [here](https://github.com/NativeScript/template-master-detail-ng/blob/master/README.md) you must use the `--appid org.nativescript.masterdetail` option exactly as specified below in order to create a runnable version of the app:
`tns create my-app-name --template https://github.com/NativeScript/template-master-detail-ng.git --appid org.nativescript.masterdetail`

Btw, in order for the app to work with full capabilities you should specify "y" on the Storage config question during Firebase configuration. We will be working on improving this experience with some kind of post-install scripts.

As for removing firebase -- it is certainly possible but then you would be left with a non-functional app as the sole purpose of this app template is to demonstrate NativeScript & Firebase integration. Could you elaborate a bit more what kind of app template are you looking for so we can take this into account when planning additional templates to implement in the future?

**Comment by lini** [comment]
If you don't want to use Firebase, you can also take a look at the "hello world" template -> [template-hello-world-ng](https://github.com/NativeScript/template-hello-world-ng). It offers similar functionality to this one but does not connect to an external data source. 

Also, we will be offering more data templates in the future (for example using [Kinvey](https://www.kinvey.com/)).

**Comment by rugdealer** [comment]
Thanks for the responses. I ended up using another template.
